load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//.bazel:defs.bzl", "go_test")

go_library(
    name = "extdata",
    srcs = [
        "hashes.go",
        "verify.go",
    ],
    embedsrcs = [
        "fuji.json",
        "mainnet.json",
    ],
    importpath = "github.com/ava-labs/avalanchego/vms/saevm/cchain/extdata",
    visibility = ["//visibility:public"],
    deps = [
        "//graft/coreth/plugin/evm/customtypes",
        "//utils/constants",
        "@com_github_ava_labs_libevm//common",
        "@com_github_ava_labs_libevm//core/types",
    ],
)

go_test(
    name = "extdata_test",
    srcs = ["extdata_test.go"],
    embed = [":extdata"],
    deps = [
        "//graft/coreth/plugin/evm/customtypes",
        "//utils/constants",
        "@com_github_ava_labs_libevm//common",
        "@com_github_ava_labs_libevm//core/types",
        "@com_github_ava_labs_libevm//trie",
        "@com_github_stretchr_testify//require",
    ],
)

package(default_visibility = [
    "//vms/saevm/cchain:__subpackages__",
    "//vms/saevm/cchain:external_consumers",
])
